2020-04-21 00:22:24,416 [12] ERROR DataAccess.LogManager - Something went wrong in DataAccess/Implementation/LinkedOrganizationDAO: 
MySql.Data.MySqlClient.MySqlException (0x80004005): Parameter '@state' has already been defined.
   en MySql.Data.MySqlClient.MySqlParameterCollection.InternalAdd(MySqlParameter value, Int32 index)
   en MySql.Data.MySqlClient.MySqlParameterCollection.Add(MySqlParameter value)
   en DataAccess.Implementation.LinkedOrganizationDAO.SaveLinkedOrganization(LinkedOrganization linkedOrganization) en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\Implementation\LinkedOrganizationDAO.cs:línea 81
2020-04-21 00:23:35,998 [12] ERROR DataAccess.LogManager - Something went wrong in DataAccess/Implementation/LinkedOrganizationDAO: 
MySql.Data.MySqlClient.MySqlException (0x80004005): Parameter '@state' has already been defined.
   en MySql.Data.MySqlClient.MySqlParameterCollection.InternalAdd(MySqlParameter value, Int32 index)
   en MySql.Data.MySqlClient.MySqlParameterCollection.Add(MySqlParameter value)
   en DataAccess.Implementation.LinkedOrganizationDAO.SaveLinkedOrganization(LinkedOrganization linkedOrganization) en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\Implementation\LinkedOrganizationDAO.cs:línea 81
2020-04-21 00:25:34,779 [12] ERROR DataAccess.LogManager - Something went wrong in DataAccess/Implementation/LinkedOrganizationDAO: 
MySql.Data.MySqlClient.MySqlException (0x80004005): Parameter '@state' has already been defined.
   en MySql.Data.MySqlClient.MySqlParameterCollection.InternalAdd(MySqlParameter value, Int32 index)
   en MySql.Data.MySqlClient.MySqlParameterCollection.Add(MySqlParameter value)
   en DataAccess.Implementation.LinkedOrganizationDAO.SaveLinkedOrganization(LinkedOrganization linkedOrganization) en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\Implementation\LinkedOrganizationDAO.cs:línea 81
2020-04-21 00:48:46,166 [12] ERROR DataAccess.LogManager - Something went wrong in DataAccess/Implementation/LinkedOrganizationDAO: 
MySql.Data.MySqlClient.MySqlException (0x80004005): Parameter '@state' has already been defined.
   en MySql.Data.MySqlClient.MySqlParameterCollection.InternalAdd(MySqlParameter value, Int32 index)
   en MySql.Data.MySqlClient.MySqlParameterCollection.Add(MySqlParameter value)
   en DataAccess.Implementation.LinkedOrganizationDAO.UpdateLinkedOrganization(LinkedOrganization linkedOrganizationUpdated) en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\Implementation\LinkedOrganizationDAO.cs:línea 339
2020-04-21 00:49:32,369 [12] ERROR DataAccess.LogManager - Something went wrong in DataAccess/Implementation/LinkedOrganizationDAO: 
MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Parameter '@idOrganizationSectorWHERE' must be defined.
   en MySql.Data.MySqlClient.Statement.SerializeParameter(MySqlParameterCollection parameters, MySqlPacket packet, String parmName, Int32 parameterIndex)
   en MySql.Data.MySqlClient.Statement.InternalBindParameters(String sql, MySqlParameterCollection parameters, MySqlPacket packet)
   en MySql.Data.MySqlClient.Statement.BindParameters()
   en MySql.Data.MySqlClient.PreparableStatement.Execute()
   en MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   en MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   en MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   en DataAccess.Implementation.LinkedOrganizationDAO.UpdateLinkedOrganization(LinkedOrganization linkedOrganizationUpdated) en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\Implementation\LinkedOrganizationDAO.cs:línea 345
2020-04-21 01:19:13,480 [12] ERROR DataAccess.LogManager - Something went wrong in DataAccess/Implementation/LinkedOrganizationDAO: 
MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'localhost' for user 'adminPPS' using method 'caching_sha2_password' failed with message: Access denied for user 'adminPPS'@'%' to database 'professionalpracticesd' ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'adminPPS'@'%' to database 'professionalpracticesd'
   en MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ContinueAuthentication(Byte[] data)
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   en MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   en MySql.Data.MySqlClient.NativeDriver.Open()
   en MySql.Data.MySqlClient.Driver.Open()
   en MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   en MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   en MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   en MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   en MySql.Data.MySqlClient.MySqlPool.GetConnection()
   en MySql.Data.MySqlClient.MySqlConnection.Open()
   en DataAccess.DataBase.DataBaseConnection.Connect() en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\DataBase\DataBaseConnection.cs:línea 28
   en DataAccess.DataBase.DataBaseConnection.OpenConnection() en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\DataBase\DataBaseConnection.cs:línea 40
   en DataAccess.Implementation.LinkedOrganizationDAO.SaveLinkedOrganization(LinkedOrganization linkedOrganization) en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\Implementation\LinkedOrganizationDAO.cs:línea 42
2020-04-21 01:19:40,518 [13] ERROR DataAccess.LogManager - Something went wrong in DataAccess/Implementation/OrganizationSectorDAO: 
MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'localhost' for user 'adminPPS' using method 'caching_sha2_password' failed with message: Access denied for user 'adminPPS'@'%' to database 'professionalpracticesd' ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'adminPPS'@'%' to database 'professionalpracticesd'
   en MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ContinueAuthentication(Byte[] data)
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   en MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   en MySql.Data.MySqlClient.NativeDriver.Open()
   en MySql.Data.MySqlClient.Driver.Open()
   en MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   en MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   en MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   en MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   en MySql.Data.MySqlClient.MySqlPool.GetConnection()
   en MySql.Data.MySqlClient.MySqlConnection.Open()
   en DataAccess.DataBase.DataBaseConnection.Connect() en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\DataBase\DataBaseConnection.cs:línea 28
   en DataAccess.DataBase.DataBaseConnection.OpenConnection() en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\DataBase\DataBaseConnection.cs:línea 40
   en DataAccess.Implementation.OrganizationSectorDAO.GetOrganizationSectorById(Int32 idOrganizationSector) en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\Implementation\OrganizationSectorDAO.cs:línea 77
2020-04-21 01:20:04,682 [12] ERROR DataAccess.LogManager - Something went wrong in DataAccess/Implementation/LinkedOrganizationDAO: 
MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'localhost' for user 'adminPPS' using method 'caching_sha2_password' failed with message: Access denied for user 'adminPPS'@'%' to database 'professionalpracticesd' ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'adminPPS'@'%' to database 'professionalpracticesd'
   en MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ContinueAuthentication(Byte[] data)
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   en MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   en MySql.Data.MySqlClient.NativeDriver.Open()
   en MySql.Data.MySqlClient.Driver.Open()
   en MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   en MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   en MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   en MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   en MySql.Data.MySqlClient.MySqlPool.GetConnection()
   en MySql.Data.MySqlClient.MySqlConnection.Open()
   en DataAccess.DataBase.DataBaseConnection.Connect() en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\DataBase\DataBaseConnection.cs:línea 28
   en DataAccess.DataBase.DataBaseConnection.OpenConnection() en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\DataBase\DataBaseConnection.cs:línea 40
   en DataAccess.Implementation.LinkedOrganizationDAO.SaveLinkedOrganization(LinkedOrganization linkedOrganization) en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\Implementation\LinkedOrganizationDAO.cs:línea 42
2020-04-21 23:27:33,972 [12] ERROR DataAccess.LogManager - Something went wrong in DataAccess/Implementation/LinkedOrganizationDAO: 
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UPDATE2 LinkedOrganization SET city = 'XALAPA2', email = 'promor@empresa.org.mx'' at line 1
   en MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   en MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   en MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   en MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   en MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   en MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   en MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   en DataAccess.Implementation.LinkedOrganizationDAO.UpdateLinkedOrganization(LinkedOrganization linkedOrganizationUpdated) en D:\1- INFORMACIÓN\PROYECTO PCONS\ProfessionalPracticesSystem\ProfessionalPracticesSystem\DataAccess\Implementation\LinkedOrganizationDAO.cs:línea 345
